### PR TITLE
Acception of lab3

### PR DESCRIPTION
**Pull request by MisterProper9000**

### CODE REVIEW

**Comment by daniilsavchuk** [comment]
IoU = 0.44 out of 1

**Recommendations:**
1. Double-check examples are drawn **fine** using Draw function from task definition.

**Comment by MisterProper9000** [comment]
It’s probably better to leave comments as a review, if you leave them as comments, the re-request review button does not appear

**Review by daniilsavchuk — CHANGES_REQUESTED** [review]
The latest commit is not shown by diff. Please fixe it. Diff shows like everything changed, but I know that you have a linkage to the previous code.

**Comment by daniilsavchuk** [comment]
IoU = 0.625 out of 1.0

Recommendations:
1. Focus on different shapes
2. Focus on more number of shapes in the test picture

**Review by daniilsavchuk — APPROVED** [review]
IoU = 0.81 out of 1.0

Approved

**Pull request merged**
